"""Dataclass DTOs — the API models of stapel-webhooks (never ORM instances).

The model-backed shapes (``Subscription``, ``Delivery``) are generated by
their presenters; what lives here is the envelopes that have no row behind
them.
"""
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class SubscriptionSecretDTO:
    """The one and only time a signing secret is readable.

    Returned by create and by rotate, never by a read. A secret that can be
    fetched again is a secret whose leak has no expiry — the receiver stores
    it on first sight, exactly like an API key.
    """

    id: str
    secret: str


@dataclass
class CatalogEventDTO:
    """One subscribable event, as the subscription builder needs it."""

    event: str
    module: str
    package: str
    description: str
    required: List[str] = field(default_factory=list)
    properties: List[str] = field(default_factory=list)


@dataclass
class EventCatalogDTO:
    """Everything this deployment can react to, generated from installed
    packages' ``schemas/emits/`` — never a hand-kept list."""

    events: List[CatalogEventDTO] = field(default_factory=list)
    delivery_types: List[str] = field(default_factory=list)


@dataclass
class ReplayResultDTO:
    """What a replay did: the row is queued again, from attempt zero."""

    id: str
    status: str
    next_attempt_at: Optional[str] = None
