"""Serializers for the stapel-webhooks API.

Model-backed response serializers are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); request serializers and
non-model envelopes live here.

The module-level ``SubscriptionSerializer`` / ``DeliverySerializer`` names
resolve the ACTIVE presenter once at import time — a ``STAPEL_SWAP``
override lands in both the schema and the runtime because settings are fixed
before this module loads.
"""
from __future__ import annotations

from rest_framework import serializers
from stapel_core.django.api.serializers import StapelDataclassSerializer

from .dto import EventCatalogDTO, ReplayResultDTO, SubscriptionSecretDTO
from .presenters import get_delivery_presenter, get_subscription_presenter

SubscriptionSerializer = get_subscription_presenter().serializer_class()
DeliverySerializer = get_delivery_presenter().serializer_class()


# ── Envelope responses ───────────────────────────────────────────────


class SubscriptionSecretSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = SubscriptionSecretDTO


class EventCatalogSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = EventCatalogDTO


class ReplayResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = ReplayResultDTO


# ── Requests ─────────────────────────────────────────────────────────


class SubscriptionCreateSerializer(serializers.Serializer):
    """The reaction rule, as a client writes it.

    ``filter`` keeps the design document's name on the wire even though the
    column is ``payload_filter``: the API is where the vocabulary of the
    feature lives, and "filter" is what it is called everywhere else.
    """

    event_type = serializers.CharField(max_length=128)
    delivery = serializers.CharField(max_length=32)
    target = serializers.DictField()
    filter = serializers.JSONField(required=False)
    description = serializers.CharField(max_length=255, required=False, allow_blank=True)
    workspace_id = serializers.UUIDField(required=False, allow_null=True)


class SubscriptionPatchSerializer(serializers.Serializer):
    event_type = serializers.CharField(max_length=128, required=False)
    delivery = serializers.CharField(max_length=32, required=False)
    target = serializers.DictField(required=False)
    filter = serializers.JSONField(required=False)
    description = serializers.CharField(max_length=255, required=False, allow_blank=True)
    is_active = serializers.BooleanField(required=False)


class SubscriptionListQuerySerializer(serializers.Serializer):
    event_type = serializers.CharField(max_length=128, required=False)
    is_active = serializers.BooleanField(required=False, allow_null=True)
    limit = serializers.IntegerField(required=False, min_value=1)


class DeliveryListQuerySerializer(serializers.Serializer):
    status = serializers.ChoiceField(
        choices=["pending", "retrying", "succeeded", "dead"], required=False
    )
    limit = serializers.IntegerField(required=False, min_value=1)


__all__ = [
    "DeliveryListQuerySerializer",
    "DeliverySerializer",
    "EventCatalogSerializer",
    "ReplayResultSerializer",
    "SubscriptionCreateSerializer",
    "SubscriptionListQuerySerializer",
    "SubscriptionPatchSerializer",
    "SubscriptionSecretSerializer",
    "SubscriptionSerializer",
]
