"""Initial schema of the reaction layer: the rule, and the evidence."""
# Generated by Django 6.0.7 on 2026-08-24 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('delivery', models.CharField(max_length=32)),
                ('target', models.JSONField(default=dict)),
                ('payload_filter', models.JSONField(blank=True, default=dict)),
                ('secret', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhooks_subscription',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('event_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('dead', 'Dead-lettered')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.subscription')),
            ],
            options={
                'db_table': 'webhooks_delivery',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['event_type', 'is_active'], name='wh_sub_event_active'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner_id', '-created_at'], name='wh_sub_owner_time'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='wh_del_status_next'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['subscription', '-created_at'], name='wh_del_sub_time'),
        ),
    ]
